### ISSUE TITLE
EOL symbol (\n) injected in the database username

### ISSUE THREAD

**Issue by jonathan-duval** [Zooz/predator#512]
**Describe the bug**
During an helm chart installation, it seem an EOL symbol (\n) is injected somewhere in the database username.

Error returned by the pod
```json
{
   "level":50,
   "time":1603200432313,
   "pid":1,
   "hostname":"predator-6dbf589d85-b8fs6",
   "name":"predator",
   "name":"SequelizeAccessDeniedError",
   "parent":{
      "code":"ER_ACCESS_DENIED_ERROR",
      "errno":1045,
      "sqlState":"28000",
      "sqlMessage":"Access denied for user 'predator\n'@***.***.***.***' (using password: YES)"
   },
   "original":{
      "code":"ER_ACCESS_DENIED_ERROR",
      "errno":1045,
      "sqlState":"28000",
      "sqlMessage":"Access denied for user 'predator\n'@'***.***.***.***' (using password: YES)"
   },
   "stack":"SequelizeAccessDeniedError: Access denied for user 'predator\n'@'***.***.***.***' (using password: YES)\n    at /usr/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19\n    at tryCatcher (/usr/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/usr/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/usr/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/usr/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/usr/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/usr/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/usr/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:456:21)",
   "type":"Error",
   "msg":"Encountered an error during start up"
}
```
**To Reproduce**
Install via helm chart on k8s gke 
`helm upgrade --install predator zooz/predator -f 20-tools/variables/predator.yml  --version 1.5.2 -n tools`
20-tools/variables/predator.yml 
```yaml
intervalCleanupFinishedContainers: 600000
allowInsecureTls: "true"
persistence.enabled: "true"
database:
  type: MYSQL
  name: "predator-database"
  username: "cHJlZGF0b3IK"
  password: "cHJlZGF0b3IK"
  address: "***.***.***.***"
```
`echo "predator" | base64 - ` => cHJlZGF0b3IK
Test realised with MYSQL 5.6 and POSTGRE 12

I already check the generated secret and the data inside seem to be sane.
```yaml
apiVersion: v1
data:
  DATABASE_PASSWORD: cHJlZGF0b3IK
  DATABASE_USERNAME: cHJlZGF0b3IK
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: predator
    meta.helm.sh/release-namespace: tools
  creationTimestamp: "2020-10-20T13:27:03Z"
  labels:
    app: predator
    app.kubernetes.io/managed-by: Helm
    chart: predator-1.5.2
    heritage: Helm
    release: predator
  name: predator
  namespace: tools
  resourceVersion: "11293286"
  selfLink: /api/v1/namespaces/tools/secrets/predator
  uid: 05a6a64a-62a0-447e-8209-52cf9f450699
type: Opaque
```

**Expected behavior**
A clear database username

**Version:**
 - Predator:1.5.4
 - Predator-runner 1.54
 - Helm chart 1.5.2
 - helm v3.3.4
 - Database POSTGRE 12 and MYSQL 5.6
 - k8s gke 1.16

I stay available if something is not clear or if I forgot something

**Comment by enudler** [comment]
hi @jonathan-duval 
predator in base 64
without new line: `cHJlZGF0b3I=`
with a new line: `cHJlZGF0b3IK`

I used this website to debug it:
https://www.base64encode.org/

**Comment by jonathan-duval** [comment]
Hello @enudler I missed it :)
Thx for the tips, I test it and, obviously, it solve my problem :+1: 
I close the issue.
