### ISSUE TITLE
errorMissingColumn with Postgresql in Helm

### ISSUE THREAD

**Issue by Kampfmoehre** [Zooz/predator#569]
**Describe the bug**
Unable to use the Predator UI.

**To Reproduce**
We have installed Predator via the [Helm Chart](https://artifacthub.io/packages/helm/zooz/predator) (upgraded from an older installation) in our Kubernetes cluster. The Helm command was running successful, however the UI is showing an error popup when visited (see below).

The logs show the following error:
```json
{
  "level": 50,
  "time": 1615802197561,
  "pid": 1,
  "hostname": "predator-64cb4888ff-2fwwx",
  "name": "predator",
  "name": "SequelizeDatabaseError",
  "parent": {
    "length": 128,
    "name": "error",
    "severity": "ERROR",
    "code": "42703",
    "position": "656",
    "file": "parse_relation.c",
    "line": "3349",
    "routine": "errorMissingColumn",
    "sql": "SELECT \"report\".*, \"subscribers\".\"runner_id\" AS \"subscribers.runner_id\", \"subscribers\".\"phase_status\" AS \"subscribers.phase_status\", \"subscribers\".\"last_stats\" AS \"subscribers.last_stats\", \"subscribers\".\"created_at\" AS \"subscribers.created_at\", \"subscribers\".\"updated_at\" AS \"subscribers.updated_at\", \"subscribers\".\"report_report_id\" AS \"subscribers.reportReportId\" FROM (SELECT \"report\".\"report_id\", \"report\".\"test_id\", \"report\".\"job_id\", \"report\".\"revision_id\", \"report\".\"test_type\", \"report\".\"test_name\", \"report\".\"test_description\", \"report\".\"last_updated_at\", \"report\".\"start_time\", \"report\".\"notes\", \"report\".\"test_configuration\", \"report\".\"phase\", \"report\".\"benchmark_weights_data\", \"report\".\"score\", \"report\".\"is_favorite\", \"report\".\"context_id\" FROM \"reports\" AS \"report\" ORDER BY \"report\".\"start_time\" DESC LIMIT 200) AS \"report\" LEFT OUTER JOIN \"subscribers\" AS \"subscribers\" ON \"report\".\"report_id\" = \"subscribers\".\"report_report_id\" ORDER BY \"report\".\"start_time\" DESC;"
  },
  "original": {
    "length": 128,
    "name": "error",
    "severity": "ERROR",
    "code": "42703",
    "position": "656",
    "file": "parse_relation.c",
    "line": "3349",
    "routine": "errorMissingColumn",
    "sql": "SELECT \"report\".*, \"subscribers\".\"runner_id\" AS \"subscribers.runner_id\", \"subscribers\".\"phase_status\" AS \"subscribers.phase_status\", \"subscribers\".\"last_stats\" AS \"subscribers.last_stats\", \"subscribers\".\"created_at\" AS \"subscribers.created_at\", \"subscribers\".\"updated_at\" AS \"subscribers.updated_at\", \"subscribers\".\"report_report_id\" AS \"subscribers.reportReportId\" FROM (SELECT \"report\".\"report_id\", \"report\".\"test_id\", \"report\".\"job_id\", \"report\".\"revision_id\", \"report\".\"test_type\", \"report\".\"test_name\", \"report\".\"test_description\", \"report\".\"last_updated_at\", \"report\".\"start_time\", \"report\".\"notes\", \"report\".\"test_configuration\", \"report\".\"phase\", \"report\".\"benchmark_weights_data\", \"report\".\"score\", \"report\".\"is_favorite\", \"report\".\"context_id\" FROM \"reports\" AS \"report\" ORDER BY \"report\".\"start_time\" DESC LIMIT 200) AS \"report\" LEFT OUTER JOIN \"subscribers\" AS \"subscribers\" ON \"report\".\"report_id\" = \"subscribers\".\"report_report_id\" ORDER BY \"report\".\"start_time\" DESC;"
  },
  "sql": "SELECT \"report\".*, \"subscribers\".\"runner_id\" AS \"subscribers.runner_id\", \"subscribers\".\"phase_status\" AS \"subscribers.phase_status\", \"subscribers\".\"last_stats\" AS \"subscribers.last_stats\", \"subscribers\".\"created_at\" AS \"subscribers.created_at\", \"subscribers\".\"updated_at\" AS \"subscribers.updated_at\", \"subscribers\".\"report_report_id\" AS \"subscribers.reportReportId\" FROM (SELECT \"report\".\"report_id\", \"report\".\"test_id\", \"report\".\"job_id\", \"report\".\"revision_id\", \"report\".\"test_type\", \"report\".\"test_name\", \"report\".\"test_description\", \"report\".\"last_updated_at\", \"report\".\"start_time\", \"report\".\"notes\", \"report\".\"test_configuration\", \"report\".\"phase\", \"report\".\"benchmark_weights_data\", \"report\".\"score\", \"report\".\"is_favorite\", \"report\".\"context_id\" FROM \"reports\" AS \"report\" ORDER BY \"report\".\"start_time\" DESC LIMIT 200) AS \"report\" LEFT OUTER JOIN \"subscribers\" AS \"subscribers\" ON \"report\".\"report_id\" = \"subscribers\".\"report_report_id\" ORDER BY \"report\".\"start_time\" DESC;",
  "stack": "SequelizeDatabaseError: column report.benchmark_weights_data does not exist\n at Query.formatError (/usr/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n at /usr/node_modules/sequelize/lib/dialects/postgres/query.js:72:18\nat tryCatcher (/usr/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/usr/node_modules/bluebird/js/release/promise.js:547:31)\n at Promise._settlePromise (/usr/node_modules/bluebird/js/release/promise.js:604:18)\n at Promise._settlePromise0 (/usr/node_modules/bluebird/js/release/promise.js:649:10)\n at Promise._settlePromises (/usr/node_modules/bluebird/js/release/promise.js:725:18)\n at _drainQueueStep (/usr/node_modules/bluebird/js/release/async.js:93:12)\n at _drainQueue (/usr/node_modules/bluebird/js/release/async.js:86:9)\n at Async._drainQueues (/usr/node_modules/bluebird/js/release/async.js:102:5)\n at Immediate.Async.drainQueues [as _onImmediate] (/usr/node_modules/bluebird/js/release/async.js:15:14)\n at processImmediate (internal/timers.js:456:21)",
  "type": "Error",
  "msg": "Failure"
}
```
When I take a look in the databse I can confirm there is indeed no column `benchmark_weights_data` in the `reports` table. I can see the following in the logs on application startup:

```
(sequelize) Warning: PostgreSQL does not support TEXT with options. Plain `TEXT` will be used instead.
--
Mon, 15 Mar 2021 10:54:57 | >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
Mon, 15 Mar 2021 10:54:57 | {"level":30,"time":1615802097980,"pid":1,"hostname":"predator-64cb4888ff-2fwwx","name":"predator","msg":"kubernetes token from env var was not provided. will use: /var/run/secrets/kubernetes.io/serviceaccount/token"}
```

**Expected behavior**
The UI works as expected.

**Screenshots**
![Predator Error](https://user-images.githubusercontent.com/14077931/111138936-d0c7df80-8580-11eb-8553-c350fa31dc9a.png)

**Version:**
 - Predator: 1.5.2
 - Predator-runner [1.5]
 - Database [e.g. Postgres]
 - Kubernetes: v1.19.4
 - Installed using Rancher cluster explorer (that is using Helm v3). Initially it was installed via Rancher Cluster manager that was using Helm v2.

**Additional context**
I also tried with the 1.6.0 docker image but the error remains.

**Comment by enudler** [comment]
@NivLipetz it seems we missed this column in our upgrade scripts

**Comment by Kampfmoehre** [comment]
For info:
After I added the column myself with `alter table reports add "benchmark_weights_data" TEXT NULL DEFAULT NULL;` Predator would also complain about the `score` column. So I also added it via `alter table reports add "score" float8 NULL DEFAULT NULL;` and now Predator is working.

**Comment by NivLipetz** [comment]
@Kampfmoehre good timing, we just merged this bug fix and will release version 1.6.1 with both score and benchmark_weights_data added to the db migrations script. 
Thanks for the issue submitted!

**Comment by Kampfmoehre** [comment]
Thank you for the quick fix and response, I will check that version. Any info on when it would become available in the helm chart? It still comes with the 1.5.2 version.

**Comment by NivLipetz** [comment]
we will release an updated helm chart for 1.6.x later today, i'll update here once we do
